#!/bin/bash
exec 2>&1

source /usr/sbin/b-log.sh
B_LOG --stdout true
DOCKER_LOG_LEVEL=${DOCKER_LOG_LEVEL:-INFO}
eval LOG_LEVEL_${DOCKER_LOG_LEVEL}


# A hack to redirect syslog to stdout.
# This is necessary because haproxy only logs to syslog.
ln -sf /proc/$$/fd/1 /var/log/container_stdout

cp /marathon-lb/rsyslog/rsyslog.conf /etc/rsyslog.conf

# Start rsyslog service
INFO $(service rsyslog start) 

while true; do sleep 0.5; done