#!/bin/sh
exec 2>&1
PIDFILE="/tmp/haproxy.pid"

reload() {
  echo "Reloading haproxy"
  if ! haproxy -c -f /marathon-lb/haproxy.cfg; then
    echo "Invalid config"
    return 1
  fi
  haproxy -p $PIDFILE -f /marathon-lb/haproxy.cfg -sf $(cat $PIDFILE)
}

haproxy -p $PIDFILE -f /marathon-lb/haproxy.cfg

trap reload SIGHUP
while true; do sleep 1; done
